### ISSUE TITLE
Fungus analysis

### ISSUE THREAD

**Issue by fabianomenegidio** [TBroTeam/Tutorial#2]
I am working with a fungus and have discovered that the Mercator is specific to a plant.

Do I need to load Mercator data? Can I disable this option?

**Comment by iimog** [comment]
Hi @fabianomenegidio your right, Mercator is plant specific.
But you don't have to load Mercator data. You can just skip this step.
In fact none of the annotation types is required for TBro to work.
The only exception is `tbro-import sequence_ids` which is the bare minimum.

This fact should be stated clearly in the tutorial.
