### ISSUE TITLE
aggregator_CountMat.pl

### ISSUE THREAD

**Issue by fabianomenegidio** [TBroTeam/Tutorial#3]
Could you provide the aggregator_CountMat.pl script? I am doing with another organism and I have followed all the complete steps.

Tnx

**Comment by iimog** [comment]
Hi @fabianomenegidio ,

thanks for the notification that this script is missing. I added it to the [TBro](https://github.com/TBroTeam/TBro) repository in `src/cli/helper`
You can directly download the script [here](https://raw.githubusercontent.com/TBroTeam/TBro/master/src/cli/helper/aggregator_CountMat.pl).
Let me know if you have any further problems.

**Comment by fbemm** [comment]
In case you are running the latest Trinity release you probably should use the aggregation tool that comes a long with it (https://github.com/trinityrnaseq/trinityrnaseq/blob/master/util/abundance_estimates_to_matrix.pl).
